### ISSUE TITLE
el-get can not find a recipe for package "rcodetools

### ISSUE THREAD

**Issue by cjuhong** [mbriggs/old-emacs.d#1]
Hi, I am using your emacs configuration:
but  i meet a problem when initialize emacs:

Warning (initialization): An error occurred while loading `/home/jeremy/.emacs.d/init.el':

error: el-get can not find a recipe for package "rcodetools".

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

**Comment by mbriggs** [comment]
Hey,

It looks like rcodetools is being brought in as a dependancy for auto-complete-ruby, even though it isn't built into el-get (I probably have an older version).

try pasting this into el-get-sources in init/init-package

``` scheme
(:name auto-complete-ruby
       :description "Auto-complete sources for Ruby"
       :type http
       :url "http://www.cx4a.org/pub/auto-complete-ruby.el"
       :depends (auto-complete))
```

hopefully that will override the el-get builtin recipe and not die

Didn't realize anyone else was using this, it changes a lot so I am sorry in advance if I break anything for you :)

**Comment by cjuhong** [comment]
Hi,

I find you have comment the five lines in  init/init-packages.el ;

;(:name auto-complete-ruby
;       :description "Auto-complete sources for Ruby"
;       :type http
;       :url "http://www.cx4a.org/pub/auto-complete-ruby.el"
;       :depends (auto-complete))

after I delete the semicolon, the error still there.

2012/9/4 Matt Briggs notifications@github.com

> Hey,
> 
> It looks like rcodetools is being brought in as a dependancy for
> auto-complete-ruby, even though it isn't built into el-get (I probably have
> an older version).
> 
> try pasting this into el-get-sources in init/init-package
> 
> (:name auto-complete-ruby
>        :description "Auto-complete sources for Ruby"
>        :type http
>        :url "http://www.cx4a.org/pub/auto-complete-ruby.el"
>        :depends (auto-complete))
> 
> hopefully that will override the el-get builtin recipe and not die
> 
> Didn't realize anyone else was using this, it changes a lot so I am sorry
> in advance if I break anything for you :)
> 
> ¡ª
> Reply to this email directly or view it on GitHubhttps://github.com/mbriggs/.emacs.d/issues/1#issuecomment-8251837.

## 

ê°lÅd Jeremy
E-Mail:cjuhong@gmail.com

**Comment by cjuhong** [comment]
Hi ,

the error  did not show again.

sorry for bothering you and thanks a lot .

Jeremy

2012/9/4 cjuhong@gmail.com

> Hi,
> 
> I find you have comment the five lines in  init/init-packages.el ;
> 
> ;(:name auto-complete-ruby
> ;       :description "Auto-complete sources for Ruby"
> ;       :type http
> ;       :url "http://www.cx4a.org/pub/auto-complete-ruby.el"
> ;       :depends (auto-complete))
> 
> after I delete the semicolon, the error still there.
> 
> 2012/9/4 Matt Briggs notifications@github.com
> 
> > Hey,
> > 
> > It looks like rcodetools is being brought in as a dependancy for
> > auto-complete-ruby, even though it isn't built into el-get (I probably have
> > an older version).
> > 
> > try pasting this into el-get-sources in init/init-package
> > 
> > (:name auto-complete-ruby
> >        :description "Auto-complete sources for Ruby"
> >        :type http
> >        :url "http://www.cx4a.org/pub/auto-complete-ruby.el"
> >        :depends (auto-complete))
> > 
> > hopefully that will override the el-get builtin recipe and not die
> > 
> > Didn't realize anyone else was using this, it changes a lot so I am sorry
> > in advance if I break anything for you :)
> > 
> > ¡ª
> > Reply to this email directly or view it on GitHubhttps://github.com/mbriggs/.emacs.d/issues/1#issuecomment-8251837.
> 
> ## 
> 
> ê°lÅd Jeremy
> E-Mail:cjuhong@gmail.com

## 

ê°lÅd Jeremy
E-Mail:cjuhong@gmail.com

**Comment by mbriggs** [comment]
Awesome, glad I could help :D
